### ISSUE TITLE
Remove `numberOfEggsFrame` field from the `Hive` class and use `eggsFrames.size()` instead

### ISSUE THREAD

**Issue by andreiursudev** [MarianBastiurea/life-of-bees#13]
Keeping a separate variable to store the `numberOfEggsFrame` requires unnecessary extra work and can easily get out of sync with the real number of `numberOfEggsFrame` and cause bugs, for example in the `Apiary#hibernate` you set `hive.setNumberOfEggsFrame(4);` even though the real number of eggFrames could be different because of previous changes.

**Comment by MarianBastiurea** [comment]
done
