### ISSUE TITLE
Encapsulate `EggsBatch` as a implementation detail

### ISSUE THREAD

**Issue by andreiursudev** [MarianBastiurea/life-of-bees#15]
`EggsBatch` is an implementation detail and should not be exposed.
Create a package named `com.marianbastiurea.lifeofbees.eggframe` and place in it the `EggsBatch` and the `EggsFrame` classes. 
Add a `List<EggsBatch> eggBatches` field to the  `EggsFrame` class.
Make class `EggsBatch` package private and don't expose its details outside `EggsFrame` class.

Remove the `numberOfEggs` field  from  `EggsFrame`  class and instead expose a method that counts all the eggs in the `eggBatches` list and returns the total number of eggs in the frame.

**Comment by MarianBastiurea** [comment]
done
